[theme]
primaryColor = "#38bdf8"
textColor = "#f8fafc"

# Latar belakang utama aplikasi kamu
backgroundColor = "#0f172a" 

# TRIKNYA DI SINI: Diubah menjadi warna navy yang sangat gelap (hampir menyatu dengan background)
secondaryBackgroundColor = "#131b2e"
